(()=>{'use strict';
const OWNER='farrokhzad743@gmail.com',cfg=window.SITE_CONFIG||{};
const db=window.supabase&&cfg.supabaseUrl&&cfg.supabaseAnonKey?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
const $=id=>document.getElementById(id);let currentUser=null,news=[],docs=[],buttons=[],editingNewsId=null,editingDocId=null,editingButtonId=null,content={};
const esc=v=>String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[m]));
const arr=v=>{if(Array.isArray(v))return v.filter(Boolean);if(!v)return[];try{let x=JSON.parse(v);if(Array.isArray(x))return x.filter(Boolean)}catch{}return String(v).split(/\r?\n|,/).map(x=>x.trim()).filter(Boolean)};
const today=()=>new Intl.DateTimeFormat('fa-IR-u-ca-persian',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:'Asia/Tehran'}).format(new Date());
function msg(t,bad=false){const e=$('adminStatus');if(e){e.textContent=t;e.className='status '+(bad?'error':'ok')}}function loginMsg(t,bad=false){const e=$('loginStatus');if(e){e.textContent=t;e.className='status '+(bad?'error':'ok')}}
function showLogin(){$('loginCard').classList.remove('hidden');$('panel').classList.add('hidden')}function showPanel(){$('loginCard').classList.add('hidden');$('panel').classList.remove('hidden')}
async function send(){if(!db)return loginMsg('config.js یا اتصال Supabase درست نیست.',true);const e=$('email').value.trim().toLowerCase();if(e!==OWNER)return loginMsg('این ایمیل اجازه ورود به پنل مدیریت را ندارد.',true);$('sendLogin').disabled=true;loginMsg('در حال ارسال کد ورود...');const {error}=await db.auth.signInWithOtp({email:e,options:{shouldCreateUser:true}});$('sendLogin').disabled=false;if(error)return loginMsg(error.message,true);$('otpBox').classList.remove('hidden');$('changeEmail').classList.remove('hidden');loginMsg('کد ورود ارسال شد.');$('otpCode').focus()}
async function verify(){const e=$('email').value.trim().toLowerCase(),token=$('otpCode').value.trim();if(e!==OWNER)return loginMsg('این ایمیل اجازه ورود به پنل مدیریت را ندارد.',true);if(!token)return loginMsg('کد ورود را وارد کنید.',true);const {data,error}=await db.auth.verifyOtp({email:e,token,type:'email'});if(error)return loginMsg(error.message,true);if(String(data.user?.email||'').toLowerCase()!==OWNER){await db.auth.signOut();return loginMsg('این حساب مالک نیست.',true)}currentUser=data.user;showPanel();$('who').textContent='مالک: '+OWNER;await loadAll()}
async function session(){if(!db)return showLogin();const {data}=await db.auth.getSession();if(String(data.session?.user?.email||'').toLowerCase()===OWNER){currentUser=data.session.user;showPanel();$('who').textContent='مالک: '+OWNER;await loadAll()}else showLogin()}
async function loadContent(){const {data,error}=await db.from('site_content').select('*');if(error){msg('خطا در محتوای سایت: '+error.message,true);return}content={};(data||[]).forEach(r=>content[r.slug||r.key]=r);const s=content.site||{};const a=content.ashayer||{};const c=content.cooperative||{};const ab=content.about||{};$('siteTitle').value=s.title||'شرکت تعاونی عشایری کوه نور کهگیلویه';$('siteDate').value=today();$('logoRight').value=s.excerpt||'';$('logoLeft').value=s.body||'';$('ashTitle').value=a.title||'عشایر؛ سرمایه ملّی';$('ashExcerpt').value=a.excerpt||'';$('ashBody').value=a.body||'';$('coopTitle').value=c.title||'چگونگی تعاونی';$('coopExcerpt').value=c.excerpt||'';$('coopBody').value=c.body||'';$('aboutTitle').value=ab.title||'درباره ما';$('aboutBody').value=ab.body||''}
async function loadNews(){const r=await db.from('news').select('*').order('created_at',{ascending:false});if(r.error)return msg('خطا در اخبار: '+r.error.message,true);news=r.data||[];renderNews()}
function renderNews(){$('newsAdminList').innerHTML=news.length?news.map(n=>`<div class=item><div class=item-head><div><b>${esc(n.title)}</b><div>${esc(n.date||'')}</div></div><div class=row><button class="btn light" data-edit-news="${esc(n.id)}">ویرایش</button><button class="btn red" data-delete-news="${esc(n.id)}">حذف</button></div></div>${arr(n.images||n.image_url).slice(0,1).map(u=>`<img class=thumb src="${esc(u)}">`).join('')}<div>${esc(n.excerpt||n.text||'')}</div></div>`).join(''):'<p>خبری ثبت نشده است.</p>'}
function openNews(id=null){editingNewsId=id;$('newsEditor').classList.remove('hidden');const n=id&&news.find(x=>String(x.id)===String(id));$('newsTitle').value=n?.title||'';$('newsDate').value=n?.date||today();$('newsExcerpt').value=n?.excerpt||n?.text||'';$('newsBody').value=n?.body||n?.content||'';$('newsImages').value='';$('selectedFiles').textContent=n?'تصاویر قبلی حفظ می‌شوند.':''}
async function uploadFiles(files,folder){const urls=[];for(const f of files){const safe=f.name.replace(/[^\w.\-]+/g,'_');const path=`${folder}/${Date.now()}-${Math.random().toString(36).slice(2)}-${safe}`;const up=await db.storage.from(cfg.storageBucket||'site-media').upload(path,f,{cacheControl:'31536000',upsert:false});if(up.error)throw up.error;const p=db.storage.from(cfg.storageBucket||'site-media').getPublicUrl(path);if(p.data?.publicUrl)urls.push(p.data.publicUrl)}return urls}
async function saveNews(){const title=$('newsTitle').value.trim();if(!title)return msg('عنوان خبر را وارد کن.',true);let images=[];try{images=await uploadFiles(Array.from($('newsImages').files||[]),'news')}catch(e){return msg('آپلود تصویر انجام نشد: '+e.message,true)}const old=editingNewsId?news.find(x=>String(x.id)===String(editingNewsId)):null;const payload={title,date:editingNewsId?$('newsDate').value:today(),excerpt:$('newsExcerpt').value.trim(),body:$('newsBody').value.trim(),images:images.length?images:arr(old?.images||old?.image_url)};const r=editingNewsId?await db.from('news').update(payload).eq('id',editingNewsId):await db.from('news').insert(payload);if(r.error)return msg('ذخیره خبر انجام نشد: '+r.error.message,true);$('newsEditor').classList.add('hidden');editingNewsId=null;await loadNews();msg('خبر ذخیره شد.')}
async function deleteNews(id){if(!confirm('این خبر حذف شود؟'))return;const r=await db.from('news').delete().eq('id',id);if(r.error)return msg('حذف خبر انجام نشد: '+r.error.message,true);await loadNews();msg('خبر حذف شد.')}
async function loadDocs(){let r=await db.from('site_documents').select('*').order('sort_order',{ascending:true});if(r.error){r=await db.from('documents').select('*').order('created_at',{ascending:true})}if(r.error)return msg('خطا در اسناد: '+r.error.message,true);docs=(r.data||[]).map(d=>({...d,url:d.url||d.file_url||d.document_url||''}));renderDocs()}
function renderDocs(){$('docsList').innerHTML=docs.length?docs.map(d=>`<div class=item><div class=item-head><div><b>${esc(d.title)}</b><div>${esc(d.url||'')}</div></div><div class=row><button class="btn light" data-edit-doc="${esc(d.id)}">ویرایش</button><button class="btn red" data-delete-doc="${esc(d.id)}">حذف</button></div></div></div>`).join(''):'<p>سندی ثبت نشده است.</p>'}
function openDoc(id=null){editingDocId=id;$('docEditor').classList.remove('hidden');const d=id&&docs.find(x=>String(x.id)===String(id));$('docTitle').value=d?.title||'';$('docFile').value='';$('docCurrent').textContent=d?.url?'فایل فعلی حفظ می‌شود مگر فایل جدید انتخاب کنی.':''}
async function saveDoc(){const title=$('docTitle').value.trim(),file=$('docFile').files[0],old=editingDocId&&docs.find(x=>String(x.id)===String(editingDocId));if(!title)return msg('عنوان سند را وارد کن.',true);let url=old?.url||'';try{if(file)url=(await uploadFiles([file],'documents'))[0]}catch(e){return msg('آپلود سند انجام نشد: '+e.message,true)}if(!url)return msg('فایل سند را انتخاب کن.',true);let r;if(editingDocId){r=await db.from('site_documents').update({title,url,updated_at:new Date().toISOString()}).eq('id',editingDocId)}else{r=await db.from('site_documents').insert({title,url,sort_order:docs.length})}if(r.error)return msg('ذخیره سند انجام نشد: '+r.error.message,true);$('docEditor').classList.add('hidden');editingDocId=null;await loadDocs();msg('سند ذخیره شد.')}
async function deleteDoc(id){if(!confirm('این سند حذف شود؟'))return;const r=await db.from('site_documents').delete().eq('id',id);if(r.error)return msg('حذف سند انجام نشد: '+r.error.message,true);await loadDocs();msg('سند حذف شد.')}
async function loadButtons(){const r=await db.from('site_buttons').select('*').order('sort_order',{ascending:true});if(r.error)return msg('خطا در دکمه‌ها: '+r.error.message,true);buttons=r.data||[];renderButtons()}
function renderButtons(){$('buttonsList').innerHTML=buttons.length?buttons.map(b=>`<div class=item><div class=item-head><div><b>${esc(b.label)}</b><div>${esc(b.target_value||b.target||'')}</div></div><div class=row><button class="btn light" data-edit-button="${esc(b.id)}">ویرایش</button><button class="btn red" data-delete-button="${esc(b.id)}">حذف</button></div></div></div>`).join(''):'<p>دکمه‌ای ثبت نشده است.</p>'}
function openButton(id=null){editingButtonId=id;$('buttonEditor').classList.remove('hidden');const b=id&&buttons.find(x=>String(x.id)===String(id));$('buttonLabel').value=b?.label||'';$('buttonTarget').value=b?.target_value||b?.target||''}
async function saveButton(){const label=$('buttonLabel').value.trim(),target=$('buttonTarget').value.trim();if(!label)return msg('متن دکمه را وارد کن.',true);const payload={label,target_value:target,target_type:/^https?:\/\//i.test(target)?'url':'content'};let r=editingButtonId?await db.from('site_buttons').update(payload).eq('id',editingButtonId):await db.from('site_buttons').insert({...payload,sort_order:buttons.length,section_slug:'custom',enabled:true});if(r.error)return msg('ذخیره دکمه انجام نشد: '+r.error.message,true);$('buttonEditor').classList.add('hidden');editingButtonId=null;await loadButtons();msg('دکمه ذخیره شد.')}
async function deleteButton(id){if(!confirm('این دکمه حذف شود؟'))return;const r=await db.from('site_buttons').delete().eq('id',id);if(r.error)return msg('حذف دکمه انجام نشد: '+r.error.message,true);await loadButtons();msg('دکمه حذف شد.')}
async function saveAll(){const values=[['site',{slug:'site',title:$('siteTitle').value.trim(),excerpt:$('logoRight').value.trim(),body:$('logoLeft').value.trim()}],['ashayer',{slug:'ashayer',title:$('ashTitle').value.trim(),excerpt:$('ashExcerpt').value.trim(),body:$('ashBody').value.trim()}],['cooperative',{slug:'cooperative',title:$('coopTitle').value.trim(),excerpt:$('coopExcerpt').value.trim(),body:$('coopBody').value.trim()}],['about',{slug:'about',title:$('aboutTitle').value.trim(),body:$('aboutBody').value.trim()}]];const rs=await Promise.all(values.map(([,v])=>db.from('site_content').upsert(v,{onConflict:'slug'})));const bad=rs.find(x=>x.error);if(bad)return msg('ذخیره تنظیمات انجام نشد: '+bad.error.message,true);await loadContent();msg('تنظیمات ذخیره شد.')}
async function loadAll(){await Promise.all([loadContent(),loadNews(),loadDocs(),loadButtons()]);msg('پنل آماده است.')}
$('sendLogin').onclick=send;$('verifyLogin').onclick=verify;$('changeEmail').onclick=()=>{$('otpBox').classList.add('hidden');$('otpCode').value='';loginMsg('');$('email').focus()};$('logout').onclick=async()=>{await db.auth.signOut();currentUser=null;showLogin()};$('previewSite').onclick=()=>window.open('index.html','_blank');$('addNews').onclick=()=>openNews();$('cancelNews').onclick=()=>$('newsEditor').classList.add('hidden');$('saveNews').onclick=saveNews;$('addDoc').onclick=()=>openDoc();$('cancelDoc').onclick=()=>$('docEditor').classList.add('hidden');$('saveDoc').onclick=saveDoc;$('addButton').onclick=()=>openButton();$('cancelButton').onclick=()=>$('buttonEditor').classList.add('hidden');$('saveButton').onclick=saveButton;$('saveAll').onclick=saveAll;
$('newsAdminList').onclick=e=>{const a=e.target.closest('[data-edit-news]'),d=e.target.closest('[data-delete-news]');if(a)openNews(a.dataset.editNews);if(d)deleteNews(d.dataset.deleteNews)};$('docsList').onclick=e=>{const a=e.target.closest('[data-edit-doc]'),d=e.target.closest('[data-delete-doc]');if(a)openDoc(a.dataset.editDoc);if(d)deleteDoc(d.dataset.deleteDoc)};$('buttonsList').onclick=e=>{const a=e.target.closest('[data-edit-button]'),d=e.target.closest('[data-delete-button]');if(a)openButton(a.dataset.editButton);if(d)deleteButton(d.dataset.deleteButton)};session();
})();
